/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DashboardWalksRouteImport } from './routes/dashboard/walks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMeetingsRouteImport } from './routes/dashboard/meetings'
import { Route as DashboardMapRouteImport } from './routes/dashboard/map'
import { Route as DashboardFriendsRouteImport } from './routes/dashboard/friends'
import { Route as DashboardDogsRouteImport } from './routes/dashboard/dogs'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard/discover'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardWalksIndexRouteImport } from './routes/dashboard/walks.index'
import { Route as DashboardMeetingsIndexRouteImport } from './routes/dashboard/meetings.index'
import { Route as DashboardChatIndexRouteImport } from './routes/dashboard/chat.index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DashboardMeetingsMeetingIdRouteImport } from './routes/dashboard/meetings.$meetingId'
import { Route as DashboardChatConversationIdRouteImport } from './routes/dashboard/chat.$conversationId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalksRoute = DashboardWalksRouteImport.update({
  id: '/walks',
  path: '/walks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeetingsRoute = DashboardMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFriendsRoute = DashboardFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDogsRoute = DashboardDogsRouteImport.update({
  id: '/dogs',
  path: '/dogs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalksIndexRoute = DashboardWalksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardWalksRoute,
} as any)
const DashboardMeetingsIndexRoute = DashboardMeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMeetingsRoute,
} as any)
const DashboardChatIndexRoute = DashboardChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardChatRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMeetingsMeetingIdRoute =
  DashboardMeetingsMeetingIdRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => DashboardMeetingsRoute,
  } as any)
const DashboardChatConversationIdRoute =
  DashboardChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => DashboardChatRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/chat': typeof DashboardChatRouteWithChildren
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/dogs': typeof DashboardDogsRoute
  '/dashboard/friends': typeof DashboardFriendsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/meetings': typeof DashboardMeetingsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/walks': typeof DashboardWalksRouteWithChildren
  '/demo/convex': typeof DemoConvexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/chat/$conversationId': typeof DashboardChatConversationIdRoute
  '/dashboard/meetings/$meetingId': typeof DashboardMeetingsMeetingIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/dashboard/chat/': typeof DashboardChatIndexRoute
  '/dashboard/meetings/': typeof DashboardMeetingsIndexRoute
  '/dashboard/walks/': typeof DashboardWalksIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/dogs': typeof DashboardDogsRoute
  '/dashboard/friends': typeof DashboardFriendsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/chat/$conversationId': typeof DashboardChatConversationIdRoute
  '/dashboard/meetings/$meetingId': typeof DashboardMeetingsMeetingIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/meetings': typeof DashboardMeetingsIndexRoute
  '/dashboard/walks': typeof DashboardWalksIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/chat': typeof DashboardChatRouteWithChildren
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/dogs': typeof DashboardDogsRoute
  '/dashboard/friends': typeof DashboardFriendsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/meetings': typeof DashboardMeetingsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/walks': typeof DashboardWalksRouteWithChildren
  '/demo/convex': typeof DemoConvexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/chat/$conversationId': typeof DashboardChatConversationIdRoute
  '/dashboard/meetings/$meetingId': typeof DashboardMeetingsMeetingIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/dashboard/chat/': typeof DashboardChatIndexRoute
  '/dashboard/meetings/': typeof DashboardMeetingsIndexRoute
  '/dashboard/walks/': typeof DashboardWalksIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/complete-profile'
    | '/dashboard'
    | '/dashboard/chat'
    | '/dashboard/discover'
    | '/dashboard/dogs'
    | '/dashboard/friends'
    | '/dashboard/map'
    | '/dashboard/meetings'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/walks'
    | '/demo/convex'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/dashboard/chat/$conversationId'
    | '/dashboard/meetings/$meetingId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/dashboard/chat/'
    | '/dashboard/meetings/'
    | '/dashboard/walks/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/complete-profile'
    | '/dashboard/discover'
    | '/dashboard/dogs'
    | '/dashboard/friends'
    | '/dashboard/map'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/demo/convex'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard'
    | '/dashboard/chat/$conversationId'
    | '/dashboard/meetings/$meetingId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/dashboard/chat'
    | '/dashboard/meetings'
    | '/dashboard/walks'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/complete-profile'
    | '/dashboard'
    | '/dashboard/chat'
    | '/dashboard/discover'
    | '/dashboard/dogs'
    | '/dashboard/friends'
    | '/dashboard/map'
    | '/dashboard/meetings'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/walks'
    | '/demo/convex'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/dashboard/chat/$conversationId'
    | '/dashboard/meetings/$meetingId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/dashboard/chat/'
    | '/dashboard/meetings/'
    | '/dashboard/walks/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoConvexRoute: typeof DemoConvexRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/walks': {
      id: '/dashboard/walks'
      path: '/walks'
      fullPath: '/dashboard/walks'
      preLoaderRoute: typeof DashboardWalksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/meetings': {
      id: '/dashboard/meetings'
      path: '/meetings'
      fullPath: '/dashboard/meetings'
      preLoaderRoute: typeof DashboardMeetingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/friends': {
      id: '/dashboard/friends'
      path: '/friends'
      fullPath: '/dashboard/friends'
      preLoaderRoute: typeof DashboardFriendsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dogs': {
      id: '/dashboard/dogs'
      path: '/dogs'
      fullPath: '/dashboard/dogs'
      preLoaderRoute: typeof DashboardDogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/walks/': {
      id: '/dashboard/walks/'
      path: '/'
      fullPath: '/dashboard/walks/'
      preLoaderRoute: typeof DashboardWalksIndexRouteImport
      parentRoute: typeof DashboardWalksRoute
    }
    '/dashboard/meetings/': {
      id: '/dashboard/meetings/'
      path: '/'
      fullPath: '/dashboard/meetings/'
      preLoaderRoute: typeof DashboardMeetingsIndexRouteImport
      parentRoute: typeof DashboardMeetingsRoute
    }
    '/dashboard/chat/': {
      id: '/dashboard/chat/'
      path: '/'
      fullPath: '/dashboard/chat/'
      preLoaderRoute: typeof DashboardChatIndexRouteImport
      parentRoute: typeof DashboardChatRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/meetings/$meetingId': {
      id: '/dashboard/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/dashboard/meetings/$meetingId'
      preLoaderRoute: typeof DashboardMeetingsMeetingIdRouteImport
      parentRoute: typeof DashboardMeetingsRoute
    }
    '/dashboard/chat/$conversationId': {
      id: '/dashboard/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/dashboard/chat/$conversationId'
      preLoaderRoute: typeof DashboardChatConversationIdRouteImport
      parentRoute: typeof DashboardChatRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardChatRouteChildren {
  DashboardChatConversationIdRoute: typeof DashboardChatConversationIdRoute
  DashboardChatIndexRoute: typeof DashboardChatIndexRoute
}

const DashboardChatRouteChildren: DashboardChatRouteChildren = {
  DashboardChatConversationIdRoute: DashboardChatConversationIdRoute,
  DashboardChatIndexRoute: DashboardChatIndexRoute,
}

const DashboardChatRouteWithChildren = DashboardChatRoute._addFileChildren(
  DashboardChatRouteChildren,
)

interface DashboardMeetingsRouteChildren {
  DashboardMeetingsMeetingIdRoute: typeof DashboardMeetingsMeetingIdRoute
  DashboardMeetingsIndexRoute: typeof DashboardMeetingsIndexRoute
}

const DashboardMeetingsRouteChildren: DashboardMeetingsRouteChildren = {
  DashboardMeetingsMeetingIdRoute: DashboardMeetingsMeetingIdRoute,
  DashboardMeetingsIndexRoute: DashboardMeetingsIndexRoute,
}

const DashboardMeetingsRouteWithChildren =
  DashboardMeetingsRoute._addFileChildren(DashboardMeetingsRouteChildren)

interface DashboardWalksRouteChildren {
  DashboardWalksIndexRoute: typeof DashboardWalksIndexRoute
}

const DashboardWalksRouteChildren: DashboardWalksRouteChildren = {
  DashboardWalksIndexRoute: DashboardWalksIndexRoute,
}

const DashboardWalksRouteWithChildren = DashboardWalksRoute._addFileChildren(
  DashboardWalksRouteChildren,
)

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRouteWithChildren
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardDogsRoute: typeof DashboardDogsRoute
  DashboardFriendsRoute: typeof DashboardFriendsRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardMeetingsRoute: typeof DashboardMeetingsRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWalksRoute: typeof DashboardWalksRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRouteWithChildren,
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardDogsRoute: DashboardDogsRoute,
  DashboardFriendsRoute: DashboardFriendsRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardMeetingsRoute: DashboardMeetingsRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWalksRoute: DashboardWalksRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoConvexRoute: DemoConvexRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
